apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::942972380686:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-JKSX87UPCZWQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::942972380686:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-20T11:30:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "834"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 18a0003b-5068-464e-b6c3-a22f2321d627
