apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::942972380686:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-68CFKKQ406IE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::942972380686:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-21T13:11:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "866"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 20d712d4-6734-4bcb-9939-c6201567033a
